# Font Configuration
font_family      Iosevka Regular
font_size        17.0

# Window padding
window_padding_width 16

# Background opacity
background_opacity 0.97

# Color scheme
foreground #a9b1d6
background #111216

# Black
color0 #000000
color8 #7f7f7f

# Red
color1 #cd0000
color9 #ff0000

# Green
color2 #00cd00
color10 #00ff00

# Yellow
color3 #cdcd00
color11 #ffff00

# Blue
color4 #0000ee
color12 #5c5cff

# Magenta
color5 #cd00cd
color13 #ff00ff

# Cyan
color6 #00cdcd
color14 #00ffff

# White
color7 #e5e5e5
color15 #ffffff
