[colors.bright]
black = "0x444b6a"
blue = "0x4da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x4aa2f7"
cyan = "0x449dab"
green = "0x4efe6a"
magenta = "0xad8ee6"
red = "0xff465e"
white = "0x787c99"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[font]
size = 9

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
opacity = 1

[window.padding]
x = 16
y = 16
